# Generated by Django 5.2.9 on 2025-12-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securefile',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_files', to='dropbox.user'),
        ),
    ]
