# Generated by Django 5.2.9 on 2025-12-18 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropbox', '0002_alter_securefile_shared_with'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='securefile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='securefile',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
