# Generated by Django 5.2.9 on 2025-12-18 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropbox', '0003_alter_securefile_owner_alter_securefile_shared_with'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
