# Generated by Django 5.2.9 on 2025-12-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=1.0, max_digits=12)),
                ('category', models.CharField(choices=[('GN', 'General'), ('EL', 'Electronics'), ('HK', 'Home & Kitchen'), ('FC', 'Fashion & Clothing'), ('BP', 'Beauty & Personal Care'), ('SO', 'Sports & Outdoors'), ('BM', 'Books & Media'), ('TG', 'Toys & Games'), ('AU', 'Automotive')], default='GN', max_length=2)),
            ],
        ),
    ]
